# Generated by Django 3.2.15 on 2022-09-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0002_vate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vate',
            new_name='Vote',
        ),
    ]
